import { loadImage } from "../canvasDrawing";

export function load_images(){
    loadImage("enchantment.png");
    loadImage("main room.png");
    loadImage("demon room.png");
    loadImage("megacano.png");
    loadImage("megacano_true.png");
    loadImage("monster.png");
    loadImage("trap.png");
    loadImage("trap_1 - Copy.png");
    loadImage("trap_1.png");
    loadImage("trap_2.png");
    loadImage("trap_3.png");
    loadImage("trap_4.png");
    loadImage("trap_5.png");
    loadImage("trap_6.png");
    loadImage("vite.svg");
    loadImage("forest/colorful rock 2.png");
    loadImage("forest/colorful rock.png");
    loadImage("forest/forest hut.png");
    loadImage("forest/hut.png");
    loadImage("forest/hut_map.png");
    loadImage("forest/large rock.png");
    loadImage("forest/large tree.png");
    loadImage("forest/map_large tree.png");
    loadImage("forest/small rock.png");
    loadImage("forest/small shrub.png");
    loadImage("forest/treasure.png");
    loadImage("forest/treasure_cutscene.png");
    loadImage("temple/book.png");
    loadImage("temple/grass.png");
    loadImage("temple/green thing.png");
    loadImage("temple/rock.png");
    loadImage("temple/temple_bg.png");
    loadImage("temple/water orb.png");
    loadImage("temple/yellow thing.png");
    loadImage("town/dead magician.png");
    loadImage("town/explorer.png");
    loadImage("town/magic shop.png");
    loadImage("town/magician.png");
    loadImage("town/map_start.png");
    loadImage("town/night.png");
    loadImage("town/tour guide.png");
    loadImage("town/tour room.png");
    loadImage("town/town destroyed.png");
    loadImage("town/town.png");
}